InlämningsUppgiftASPnetMVC/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InlämningsUppgiftASPnetMVC.Data;
using InlämningsUppgiftASPnetMVC.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace InlämningsUppgiftASPnetMVC.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ClassesController : Controller
    {
        private readonly SchoolPortalDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ClassesController(SchoolPortalDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Classes
        public async Task<IActionResult> Index()
        {
            var classes = await _context.SchoolClasses.ToListAsync();

            foreach(var schoolClass in classes)
            {
                schoolClass.Teacher = await _userManager.Users.FirstOrDefaultAsync(app => app.Id == schoolClass.TeacherId);
            }
          

            return View(classes);
        }

        // GET: Classes/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.SchoolClasses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolClass == null)
            {
                return NotFound();
            }

            return View(schoolClass);
        }

        // GET: Classes/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Teachers = await _userManager.GetUsersInRoleAsync("Teacher");
            

            return View();
        }

        // POST: Classes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClassName,TeacherId,Created")] SchoolClass schoolClass)
        {
            if (ModelState.IsValid)
            {
                schoolClass.Id = Guid.NewGuid();
                _context.Add(schoolClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(schoolClass);
        }

        // GET: Classes/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.SchoolClasses.FindAsync(id);
            if (schoolClass == null)
            {
                return NotFound();
            }
            ViewBag.Students = await _userManager.GetUsersInRoleAsync("Student");
            return View(schoolClass);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,ClassName,TeacherId,Created,SchoolClassStudents")] SchoolClass schoolClass)
        {
            if (id != schoolClass.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolClassExists(schoolClass.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(schoolClass);
        }

        // GET: Classes/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClass = await _context.SchoolClasses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schoolClass == null)
            {
                return NotFound();
            }

            return View(schoolClass);
        }

        // POST: Classes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var schoolClass = await _context.SchoolClasses.FindAsync(id);
            _context.SchoolClasses.Remove(schoolClass);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolClassExists(Guid id)
        {
            return _context.SchoolClasses.Any(e => e.Id == id);
        }
    }
}

InlämningsUppgiftASPnetMVC/Controllers/SchoolClassStudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InlämningsUppgiftASPnetMVC.Data;
using InlämningsUppgiftASPnetMVC.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace InlämningsUppgiftASPnetMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SchoolClassStudentsController : Controller
    {
        private readonly SchoolPortalDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SchoolClassStudentsController(SchoolPortalDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: SchoolClassStudents
        public IActionResult Index()
        {
            var schoolPortalDbContext =  _context.SchoolClassStudents.Include(s => s.SchoolClass);   
                                                                                                     
            return View(schoolPortalDbContext);
        }

        // GET: SchoolClassStudents/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClassStudent = await _context.SchoolClassStudents
                .Include(s => s.SchoolClass)
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (schoolClassStudent == null)
            {
                return NotFound();
            }

            return View(schoolClassStudent);
        }

        // GET: SchoolClassStudents/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Students = await _userManager.GetUsersInRoleAsync("Student");

            
            ViewData["SchoolClassId"] = new SelectList(_context.SchoolClasses, "Id", "ClassName");
            return View();
        }

        // POST: SchoolClassStudents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentId,SchoolClassId")] SchoolClassStudent schoolClassStudent)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(schoolClassStudent);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    return RedirectToAction(nameof(Index));
                    throw;
                }
            }
            ViewData["SchoolClassId"] = new SelectList(_context.SchoolClasses, "Id", "ClassName", schoolClassStudent.SchoolClassId);
            return View(schoolClassStudent);
        }

        // GET: SchoolClassStudents/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClassStudent = await _context.SchoolClassStudents.FindAsync(id);
            if (schoolClassStudent == null)
            {
                return NotFound();
            }
            ViewData["SchoolClassId"] = new SelectList(_context.SchoolClasses, "Id", "ClassName", schoolClassStudent.SchoolClassId);
            return View(schoolClassStudent);
        }

        // POST: SchoolClassStudents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("StudentId,SchoolClassId")] SchoolClassStudent schoolClassStudent)
        {
            if (id != schoolClassStudent.StudentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schoolClassStudent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolClassStudentExists(schoolClassStudent.StudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SchoolClassId"] = new SelectList(_context.SchoolClasses, "Id", "ClassName", schoolClassStudent.SchoolClassId);
            return View(schoolClassStudent);
        }

        // GET: SchoolClassStudents/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schoolClassStudent = await _context.SchoolClassStudents
                .Include(s => s.SchoolClass)
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (schoolClassStudent == null)
            {
                return NotFound();
            }

            return View(schoolClassStudent);
        }

        // POST: SchoolClassStudents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var schoolClassStudent = await _context.SchoolClassStudents.FindAsync(id);
            _context.SchoolClassStudents.Remove(schoolClassStudent);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolClassStudentExists(string id)
        {
            return _context.SchoolClassStudents.Any(e => e.StudentId == id);
        }
    }
}

InlämningsUppgiftASPnetMVC/Views/Classes/Create.cshtml
@model InlämningsUppgiftASPnetMVC.Entities.SchoolClass

@{
    ViewData["Title"] = "Create";
}
<div class="container">
    <h2 class="mt-4">Create</h2>

    <h4 class="mt-4">SchoolClass</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ClassName" class="control-label"></label>
                    <input asp-for="ClassName" class="form-control" />
                    <span asp-validation-for="ClassName" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <label asp-for="TeacherId" class="control-label"></label>
                    @Html.DropDownListFor(m => m.TeacherId, new SelectList(ViewBag.Teachers, "Id", "FullName"), "Select a Teacher")
                </div>
                
                
                <div class="form-group mt-4">
                    <label asp-for="Created" class="control-label"></label>
                    <input asp-for="Created" class="form-control" />
                    <span asp-validation-for="Created" class="text-danger"></span>
                </div>
                <div class="form-group mt-4">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
<div class="mt-4 px-2">
    <a  asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InlämningsUppgiftASPnetMVC/Views/Classes/Delete.cshtml
@model InlämningsUppgiftASPnetMVC.Entities.SchoolClass

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SchoolClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeacherId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeacherId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InlämningsUppgiftASPnetMVC/Views/Classes/Details.cshtml
@model InlämningsUppgiftASPnetMVC.Entities.SchoolClass

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SchoolClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeacherId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Teacher.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InlämningsUppgiftASPnetMVC/Views/Classes/Edit.cshtml
@model InlämningsUppgiftASPnetMVC.Entities.SchoolClass

@{
    ViewData["Title"] = "Edit";
}
<div class="container">
    <h1 class="mt-2">Edit</h1>

    <h4>SchoolClass</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group mt-2">
                    <label asp-for="ClassName" class="control-label"></label>
                    <input asp-for="ClassName" class="form-control" />
                    <span asp-validation-for="ClassName" class="text-danger"></span>
                </div>
                <div class="form-group mt-2">
                    <label asp-for="TeacherId" class="control-label"></label>
                    <input asp-for="TeacherId" class="form-control" />
                    <span asp-validation-for="TeacherId" class="text-danger"></span>
                </div>
                <div class="form-group mt-2">
                    <label asp-for="Created" class="control-label"></label>
                    <input asp-for="Created" class="form-control" />
                    <span asp-validation-for="Created" class="text-danger"></span>
                </div>
               <div class="form-group mt-4">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div class="mt-2">
        <a   asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

</div>

InlämningsUppgiftASPnetMVC/Views/Classes/Index.cshtml
@model IEnumerable<InlämningsUppgiftASPnetMVC.Entities.SchoolClass>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <h2 class="mt-4 mb-4">Class List</h2>
    <hr />
    <div class="d-flex">
        <p>
            <a class="btn btn-primary mt-2" asp-action="Create">Create Class</a>
        </p>
        <p>
            <a class="btn btn-primary m-2 " asp-controller="SchoolClassStudents" asp-action="Create">Add Students To Class</a>
        </p>
        <p>
            <a class="btn btn-primary mt-2 mb-2" asp-controller="SchoolClassStudents" asp-action="Index">Class/Student Info</a>
        </p>
    </div>
    
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ClassName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TeacherId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Created)
                </th>
              
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ClassName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Teacher.FullName)
                </td>
                <td>
                    @String.Format("{0:yyyy/MM/dd}", item.Created)
                </td>
               
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
<div class="mt-4 px-3">
    <a asp-controller="Home" asp-action="Index">Back to Homepage</a>
</div>